{
 "title": "Kubernetes Cluster Monitoring (via Prometheus)",
 "tags": [
  "kubernetes",
  "loan-prediction",
  "cluster"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Data Source", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Network I/O pressure",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{namespace=\"loan-prediction-mlops\"}[5m]))",
     "legendFormat": "Network receive"
    },
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{namespace=\"loan-prediction-mlops\"}[5m]))",
     "legendFormat": "Network transmit"
    }
   ]
  },
  {
   "title": "Cluster memory usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"loan-prediction-mlops\", container!=\"\"}) / sum(kube_node_status_capacity{resource=\"memory\"}) * 100",
     "legendFormat": "Memory Usage"
    }
   ]
  },
  {
   "title": "Cluster CPU usage (2m avg)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"loan-prediction-mlops\", container!=\"\"}[2m]))",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  {
   "title": "Cluster filesystem usage",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_fs_usage_bytes{namespace=\"loan-prediction-mlops\", container!=\"\"})",
     "legendFormat": "Filesystem Usage"
    }
   ]
  },
  {
   "title": "Pods CPU usage (2m avg)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"loan-prediction-mlops\", pod!=\"\", container!=\"\"}[2m])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Containers CPU usage (2m avg)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"loan-prediction-mlops\", container!=\"POD\", container!=\"\"}[2m])) by (pod, container)",
     "legendFormat": "{{pod}}/{{container}}"
    }
   ]
  }
 ]
}