apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: loan-prediction
  namespace: monitoring
  labels:
    release: kube-prom
spec:
  namespaceSelector:
    matchNames: ["loan-prediction-mlops"]
  selector:
    matchLabels:
      app: loan-prediction
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
