{
 "title": "Loan Prediction - FastAPI Monitoring",
 "tags": [
  "loan-prediction",
  "fastapi",
  "mlops"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Data Source", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Total requests in server",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (handler) (increase(http_requests_total{namespace=\"loan-prediction-mlops\"}[$__range]))",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "Requests created",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(http_requests_total{namespace=\"loan-prediction-mlops\"}[5m])",
     "legendFormat": "{{method}} {{handler}}"
    }
   ]
  },
  {
   "title": "Batch prediction calls",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(model_predictions_total{namespace=\"loan-prediction-mlops\"}[$__range]))",
     "legendFormat": "Total Predictions"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(http_request_duration_seconds_bucket{namespace=\"loan-prediction-mlops\"}[5m])) by (le, handler))",
     "legendFormat": "p50 - {{handler}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket{namespace=\"loan-prediction-mlops\"}[5m])) by (le, handler))",
     "legendFormat": "p95 - {{handler}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_request_duration_seconds_bucket{namespace=\"loan-prediction-mlops\"}[5m])) by (le, handler))",
     "legendFormat": "p99 - {{handler}}"
    }
   ]
  }
 ]
}